// Section 2 data — AI image vs human-drawn art.
// Read by quiz.js at startQuiz() via `typeof IMAGE_PAIRS` guard.
//
// Schema (must stay in sync with the Person 1 / Person 2 contract):
//   {
//     type: "image",
//     genre: string,
//     human: { url: string, attribution: string },
//     ai:    { url: string, attribution: string }
//   }
//
// URLs below use picsum.photos placeholder images so the layout renders
// reliably on any network. To finish the section, swap each `url` for:
//   - human side: a public-domain painting (Wikimedia Commons, museum CDN, etc.)
//   - ai side:    a real AI-generated image (the same artwork style)
// Attributions can stay as-is — they describe the intended subject.

const IMAGE_PAIRS = [
  {
    type: "image",
    genre: "Portrait",
    human: {
      url: "https://picsum.photos/seed/human-portrait/800/600",
      attribution: "Johannes Vermeer, Girl with a Pearl Earring (c. 1665)"
    },
    ai: {
      url: "https://picsum.photos/seed/ai-portrait/800/600",
      attribution: "Generated by AI"
    }
  },
  {
    type: "image",
    genre: "Landscape",
    human: {
      url: "https://picsum.photos/seed/human-landscape/800/600",
      attribution: "Katsushika Hokusai, The Great Wave off Kanagawa (c. 1831)"
    },
    ai: {
      url: "https://picsum.photos/seed/ai-landscape/800/600",
      attribution: "Generated by AI"
    }
  },
  {
    type: "image",
    genre: "Still life",
    human: {
      url: "https://picsum.photos/seed/human-stilllife/800/600",
      attribution: "Vincent van Gogh, Sunflowers (1888)"
    },
    ai: {
      url: "https://picsum.photos/seed/ai-stilllife/800/600",
      attribution: "Generated by AI"
    }
  },
  {
    type: "image",
    genre: "Surreal scene",
    human: {
      url: "https://picsum.photos/seed/human-surreal/800/600",
      attribution: "Hieronymus Bosch, The Garden of Earthly Delights (c. 1500)"
    },
    ai: {
      url: "https://picsum.photos/seed/ai-surreal/800/600",
      attribution: "Generated by AI"
    }
  },
  {
    type: "image",
    genre: "Abstract",
    human: {
      url: "https://picsum.photos/seed/human-abstract/800/600",
      attribution: "Wassily Kandinsky, Composition VIII (1923)"
    },
    ai: {
      url: "https://picsum.photos/seed/ai-abstract/800/600",
      attribution: "Generated by AI"
    }
  }
];
