// AI vs Human Text Quiz — side-by-side format
// 5 pairs (one human + one AI per genre). User picks which side is AI.

const PAIRS = [
  {
    genre: "Literary fiction",
    human: {
      text:
        "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife. However little known the feelings or views of such a man may be on his first entering a neighbourhood, this truth is so well fixed in the minds of the surrounding families, that he is considered as the rightful property of some one or other of their daughters.",
      attribution: "Jane Austen, Pride and Prejudice (1813)"
    },
    ai: {
      text:
        "It has long been observed, in the small towns and quiet drawing-rooms of the county, that a young woman of agreeable disposition cannot remain long unobserved when her circumstances are reduced. Such was the case with Miss Whitcombe, whose recent misfortunes had drawn upon her a measure of sympathy from her neighbours, and a measure of curiosity that, in truth, was rather less polite than they were willing to admit.",
      attribution: "Generated by AI (Claude)"
    }
  },
  {
    genre: "Detective fiction",
    human: {
      text:
        "In the year 1878 I took my degree of Doctor of Medicine of the University of London, and proceeded to Netley to go through the course prescribed for surgeons in the army. Having completed my studies there, I was duly attached to the Fifth Northumberland Fusiliers as Assistant Surgeon. The regiment was stationed in India at the time, and before I could join it, the second Afghan war had broken out.",
      attribution: "Arthur Conan Doyle, A Study in Scarlet (1887)"
    },
    ai: {
      text:
        "In the autumn of 1889 I returned from my service in the colonies and took rooms at a quiet address in Bloomsbury. My health, which had been much weakened by the climate, demanded a period of rest, and I had resolved to occupy myself with little more than reading and the keeping of a modest journal. It was during this interval of forced leisure that I made the acquaintance of the gentleman whose remarkable abilities form the subject of these pages.",
      attribution: "Generated by AI (Claude)"
    }
  },
  {
    genre: "Essay / opinion",
    human: {
      text:
        "I went to the woods because I wished to live deliberately, to front only the essential facts of life, and see if I could not learn what it had to teach, and not, when I came to die, discover that I had not lived. I did not wish to live what was not life, living is so dear; nor did I wish to practise resignation, unless it was quite necessary.",
      attribution: "Henry David Thoreau, Walden (1854)"
    },
    ai: {
      text:
        "There is, I have come to believe, a certain quiet dignity in choosing one's own pace through the world. We are forever urged to hurry — to produce, to acquire, to be seen producing and acquiring — and yet the deepest satisfactions of a human life seem to reward those who learn, however briefly, to step aside from the current and observe its motion from the bank.",
      attribution: "Generated by AI (Claude)"
    }
  },
  {
    genre: "Nature writing",
    human: {
      text:
        "The whole landscape showed design, like man's noblest sculptures. How wonderful the power of its beauty! Gazing awe-stricken, I might have left everything for it. Glad, endless work would then be mine tracing the forces that have brought forth its features, its giant domes and pinnacles, its forests and gardens, lakes and meadows, and glorious river cañons.",
      attribution: "John Muir, My First Summer in the Sierra (1911)"
    },
    ai: {
      text:
        "Standing at the edge of the great valley, one is struck first by the silence, and then, by degrees, by the immense and patient work that silence conceals. Every ridge, every weathered face of granite, every slow-bending pine bears witness to forces unimaginably ancient, working with a steadiness that puts our brief human striving into a humbling and clarifying perspective.",
      attribution: "Generated by AI (Claude)"
    }
  },
  {
    genre: "Poetry",
    isPoetry: true,
    human: {
      text:
        "Hope is the thing with feathers —\nThat perches in the soul —\nAnd sings the tune without the words —\nAnd never stops — at all —\n\nAnd sweetest — in the Gale — is heard —\nAnd sore must be the storm —\nThat could abash the little Bird\nThat kept so many warm —",
      attribution: "Emily Dickinson, c. 1861"
    },
    ai: {
      text:
        "Joy is a small and stubborn thing —\nIt nests within the chest —\nAnd sings a song without a name —\nAnd asks for little rest —\n\nIt grows the loudest in the dark —\nWhen silence weighs the most —\nAnd brightest burns the smallest spark\nWhen hope is nearly lost —",
      attribution: "Generated by AI (Claude)"
    }
  }
];

// ---------- state ----------
const state = {
  order: [],        // shuffled indices into PAIRS
  index: 0,         // current pair
  layouts: [],      // per-question: "A" side is "human" or "ai"
  answers: []       // per-question: user's pick — "A" or "B"
};

// ---------- helpers ----------
function shuffle(arr) {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function show(screenId) {
  document.querySelectorAll(".screen").forEach(el => el.classList.remove("active"));
  document.getElementById(screenId).classList.add("active");
}

// ---------- consent ----------
function showConsent() {
  show("consent");
}

// ---------- title ----------
function startQuiz() {
  state.order = shuffle(PAIRS.map((_, i) => i));
  state.index = 0;
  state.answers = [];
  state.layouts = state.order.map(() => (Math.random() < 0.5 ? "human" : "ai"));
  renderQuestion();
  show("quiz");
}

// ---------- question ----------
function renderQuestion() {
  const pair = PAIRS[state.order[state.index]];
  const aSide = state.layouts[state.index]; // which source is on side A

  document.getElementById("counter").textContent = `${state.index + 1} / ${PAIRS.length}`;
  document.getElementById("genre").textContent = pair.genre;

  const aText = document.getElementById("text-a");
  const bText = document.getElementById("text-b");
  const poetry = !!pair.isPoetry;

  aText.classList.toggle("poetry", poetry);
  bText.classList.toggle("poetry", poetry);

  aText.textContent = (aSide === "human" ? pair.human : pair.ai).text;
  bText.textContent = (aSide === "human" ? pair.ai : pair.human).text;

  const pct = (state.index / PAIRS.length) * 100;
  document.getElementById("progress-bar").style.width = pct + "%";
}

function answer(pick) {
  state.answers.push(pick); // "A" or "B"
  state.index++;
  if (state.index >= state.order.length) {
    show("video");
  } else {
    renderQuestion();
  }
}

// ---------- results ----------
function renderResults() {
  let correct = 0;
  state.order.forEach((pIdx, qIdx) => {
    const aSide = state.layouts[qIdx];
    const aiSide = aSide === "ai" ? "A" : "B";
    if (state.answers[qIdx] === aiSide) correct++;
  });

  document.getElementById("score").textContent =
    `You got ${correct} / ${PAIRS.length} correct.`;

  const list = document.getElementById("breakdown");
  list.innerHTML = "";

  state.order.forEach((pIdx, qIdx) => {
    const pair = PAIRS[pIdx];
    const aSide = state.layouts[qIdx];
    const aiSide = aSide === "ai" ? "A" : "B";
    const userPick = state.answers[qIdx];
    const right = userPick === aiSide;

    const aData = aSide === "human" ? pair.human : pair.ai;
    const bData = aSide === "human" ? pair.ai : pair.human;
    const aLabel = aSide === "human" ? "Human" : "AI";
    const bLabel = aSide === "human" ? "AI" : "Human";

    const item = document.createElement("li");
    item.className = "breakdown-item " + (right ? "right" : "wrong");

    item.innerHTML = `
      <div class="breakdown-head">
        <span class="mark">${right ? "✓" : "✗"}</span>
        <span class="qnum">Q${qIdx + 1}</span>
        <span class="qgenre">${pair.genre}</span>
      </div>
      <div class="pair-grid">
        <div class="pair-side ${aLabel === "AI" ? "is-ai" : "is-human"} ${userPick === "A" ? "picked" : ""}">
          <div class="side-label">Passage A — <strong>${aLabel}</strong></div>
          <div class="side-text ${pair.isPoetry ? "poetry" : ""}"></div>
          <div class="side-attr">${aData.attribution}</div>
        </div>
        <div class="pair-side ${bLabel === "AI" ? "is-ai" : "is-human"} ${userPick === "B" ? "picked" : ""}">
          <div class="side-label">Passage B — <strong>${bLabel}</strong></div>
          <div class="side-text ${pair.isPoetry ? "poetry" : ""}"></div>
          <div class="side-attr">${bData.attribution}</div>
        </div>
      </div>
      <div class="breakdown-meta">
        <strong>You picked:</strong> Passage ${userPick} (${userPick === "A" ? aLabel : bLabel})
      </div>
    `;
    item.querySelectorAll(".side-text")[0].textContent = aData.text;
    item.querySelectorAll(".side-text")[1].textContent = bData.text;
    list.appendChild(item);
  });
}

// ---------- wiring ----------
document.addEventListener("DOMContentLoaded", () => {
  document.getElementById("start-btn").addEventListener("click", showConsent);
  document.getElementById("consent-agree").addEventListener("click", startQuiz);
  document.getElementById("consent-decline").addEventListener("click", () => show("title"));
  document.getElementById("video-continue").addEventListener("click", () => {
    renderResults();
    show("results");
  });
  document.getElementById("pick-a").addEventListener("click", () => answer("A"));
  document.getElementById("pick-b").addEventListener("click", () => answer("B"));
  document.getElementById("retake-btn").addEventListener("click", () => show("title"));
});
